/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PolitykaIndexRouteImport } from './routes/polityka/index'
import { Route as NauczycielIndexRouteImport } from './routes/nauczyciel/index'
import { Route as KoszykIndexRouteImport } from './routes/koszyk/index'
import { Route as KontoIndexRouteImport } from './routes/konto/index'
import { Route as SklepProductIdRouteImport } from './routes/sklep/$productId'
import { Route as PolitykaPolicyIdRouteImport } from './routes/polityka/$policyId'
import { Route as KontoRegisterRouteImport } from './routes/konto/register'
import { Route as KontoLoginRouteImport } from './routes/konto/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitykaIndexRoute = PolitykaIndexRouteImport.update({
  id: '/polityka/',
  path: '/polityka/',
  getParentRoute: () => rootRouteImport,
} as any)
const NauczycielIndexRoute = NauczycielIndexRouteImport.update({
  id: '/nauczyciel/',
  path: '/nauczyciel/',
  getParentRoute: () => rootRouteImport,
} as any)
const KoszykIndexRoute = KoszykIndexRouteImport.update({
  id: '/koszyk/',
  path: '/koszyk/',
  getParentRoute: () => rootRouteImport,
} as any)
const KontoIndexRoute = KontoIndexRouteImport.update({
  id: '/konto/',
  path: '/konto/',
  getParentRoute: () => rootRouteImport,
} as any)
const SklepProductIdRoute = SklepProductIdRouteImport.update({
  id: '/sklep/$productId',
  path: '/sklep/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitykaPolicyIdRoute = PolitykaPolicyIdRouteImport.update({
  id: '/polityka/$policyId',
  path: '/polityka/$policyId',
  getParentRoute: () => rootRouteImport,
} as any)
const KontoRegisterRoute = KontoRegisterRouteImport.update({
  id: '/konto/register',
  path: '/konto/register',
  getParentRoute: () => rootRouteImport,
} as any)
const KontoLoginRoute = KontoLoginRouteImport.update({
  id: '/konto/login',
  path: '/konto/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/konto/login': typeof KontoLoginRoute
  '/konto/register': typeof KontoRegisterRoute
  '/polityka/$policyId': typeof PolitykaPolicyIdRoute
  '/sklep/$productId': typeof SklepProductIdRoute
  '/konto': typeof KontoIndexRoute
  '/koszyk': typeof KoszykIndexRoute
  '/nauczyciel': typeof NauczycielIndexRoute
  '/polityka': typeof PolitykaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/konto/login': typeof KontoLoginRoute
  '/konto/register': typeof KontoRegisterRoute
  '/polityka/$policyId': typeof PolitykaPolicyIdRoute
  '/sklep/$productId': typeof SklepProductIdRoute
  '/konto': typeof KontoIndexRoute
  '/koszyk': typeof KoszykIndexRoute
  '/nauczyciel': typeof NauczycielIndexRoute
  '/polityka': typeof PolitykaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/konto/login': typeof KontoLoginRoute
  '/konto/register': typeof KontoRegisterRoute
  '/polityka/$policyId': typeof PolitykaPolicyIdRoute
  '/sklep/$productId': typeof SklepProductIdRoute
  '/konto/': typeof KontoIndexRoute
  '/koszyk/': typeof KoszykIndexRoute
  '/nauczyciel/': typeof NauczycielIndexRoute
  '/polityka/': typeof PolitykaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/konto/login'
    | '/konto/register'
    | '/polityka/$policyId'
    | '/sklep/$productId'
    | '/konto'
    | '/koszyk'
    | '/nauczyciel'
    | '/polityka'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/konto/login'
    | '/konto/register'
    | '/polityka/$policyId'
    | '/sklep/$productId'
    | '/konto'
    | '/koszyk'
    | '/nauczyciel'
    | '/polityka'
  id:
    | '__root__'
    | '/'
    | '/konto/login'
    | '/konto/register'
    | '/polityka/$policyId'
    | '/sklep/$productId'
    | '/konto/'
    | '/koszyk/'
    | '/nauczyciel/'
    | '/polityka/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontoLoginRoute: typeof KontoLoginRoute
  KontoRegisterRoute: typeof KontoRegisterRoute
  PolitykaPolicyIdRoute: typeof PolitykaPolicyIdRoute
  SklepProductIdRoute: typeof SklepProductIdRoute
  KontoIndexRoute: typeof KontoIndexRoute
  KoszykIndexRoute: typeof KoszykIndexRoute
  NauczycielIndexRoute: typeof NauczycielIndexRoute
  PolitykaIndexRoute: typeof PolitykaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polityka/': {
      id: '/polityka/'
      path: '/polityka'
      fullPath: '/polityka'
      preLoaderRoute: typeof PolitykaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nauczyciel/': {
      id: '/nauczyciel/'
      path: '/nauczyciel'
      fullPath: '/nauczyciel'
      preLoaderRoute: typeof NauczycielIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koszyk/': {
      id: '/koszyk/'
      path: '/koszyk'
      fullPath: '/koszyk'
      preLoaderRoute: typeof KoszykIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konto/': {
      id: '/konto/'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof KontoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sklep/$productId': {
      id: '/sklep/$productId'
      path: '/sklep/$productId'
      fullPath: '/sklep/$productId'
      preLoaderRoute: typeof SklepProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polityka/$policyId': {
      id: '/polityka/$policyId'
      path: '/polityka/$policyId'
      fullPath: '/polityka/$policyId'
      preLoaderRoute: typeof PolitykaPolicyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konto/register': {
      id: '/konto/register'
      path: '/konto/register'
      fullPath: '/konto/register'
      preLoaderRoute: typeof KontoRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konto/login': {
      id: '/konto/login'
      path: '/konto/login'
      fullPath: '/konto/login'
      preLoaderRoute: typeof KontoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontoLoginRoute: KontoLoginRoute,
  KontoRegisterRoute: KontoRegisterRoute,
  PolitykaPolicyIdRoute: PolitykaPolicyIdRoute,
  SklepProductIdRoute: SklepProductIdRoute,
  KontoIndexRoute: KontoIndexRoute,
  KoszykIndexRoute: KoszykIndexRoute,
  NauczycielIndexRoute: NauczycielIndexRoute,
  PolitykaIndexRoute: PolitykaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
